meta_product_name: "Shelter"
meta_title: "Shelter - When Disaster strikes, you can always find Shelter"
meta_description: "Shelter is a Japanese disaster aid application to help find nearby relief shelters and communicate with others nearby to find your needs."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
